DROP DATABASE IF EXISTS java_workshop;
CREATE DATABASE java_workshop;
use java_workshop;

-- table creation
CREATE TABLE users(
    id int NOT NULL AUTO_INCREMENT,
    full_name VARCHAR(255) NOT NULL,
    type int NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    UNIQUE(email),
    PRIMARY KEY (id)
);

CREATE TABLE products(
    id int NOT NULL AUTO_INCREMENT,
    productName VARCHAR(50),
    PRIMARY KEY (id)
);

CREATE TABLE taskTypes(
    id int NOT NULL AUTO_INCREMENT,
    taskType VARCHAR(50),
    PRIMARY KEY (id)
);

CREATE TABLE environments(
    id int NOT NULL AUTO_INCREMENT,
    envName VARCHAR(50),
    PRIMARY KEY (id)
);

CREATE TABLE priority(
    id int NOT NULL AUTO_INCREMENT,
    priorityName VARCHAR(50),
    PRIMARY KEY (id)
);

CREATE TABLE status(
    id int NOT NULL AUTO_INCREMENT,
    statusName VARCHAR(50),
    PRIMARY KEY (id)
);

CREATE TABLE userTypes(
    id int NOT NULL AUTO_INCREMENT,
    userType VARCHAR(50),
    PRIMARY KEY (id)
);



CREATE TABLE tasks(
    id int NOT NULL AUTO_INCREMENT,
    taskTypeId int NOT NULL,
    productId int NOT NULL,
    envId int NOT NULL,
    requesterId int NOT NULL,
    priorityId int NOT NULL,
    open_date DATE NOT NULL,
    exec_date DATE NOT NULL,
    statusId int NOT NULL,
    qaGO bool NOT NULL,
    rollBack bool NOT NULL,
    urgent bool NOT NULL,
    additionalInfo TEXT,
    files TEXT,
    assigneeId int,
    resolved_by_Id int,
    -- you can't delete a user from the database without first assigning its tasks to some other user
    FOREIGN KEY (requesterId) REFERENCES users(id) ON DELETE RESTRICT,
    FOREIGN KEY (assigneeId) REFERENCES users(id) ON DELETE RESTRICT,
    FOREIGN KEY (resolved_by_Id) REFERENCES users(id) ON DELETE RESTRICT,
    FOREIGN KEY (taskTypeId) REFERENCES taskTypes(id) ON DELETE RESTRICT,
    FOREIGN KEY (productId) REFERENCES products(id) ON DELETE RESTRICT,
    FOREIGN KEY (envId) REFERENCES environments(id) ON DELETE RESTRICT,
    FOREIGN KEY (priorityId) REFERENCES priority(id) ON DELETE RESTRICT,
    FOREIGN KEY (statusId) REFERENCES status(id) ON DELETE RESTRICT,
    PRIMARY KEY (id)
);

-- populate some basic data
INSERT INTO userTypes (userType) VALUES ('Admin');
INSERT INTO userTypes (userType) VALUES ('Requester');
INSERT INTO userTypes (userType) VALUES ('Executor');

INSERT INTO users (full_name,type,email,password) VALUES ('David Susskind', 1, 'dchamud@gmail.com', 'bla');
INSERT INTO users (full_name,type,email,password) VALUES ('Barak Obama', 2, 'barakobama@gmail.com',  'bla');
INSERT INTO users (full_name,type,email,password) VALUES ('Luiz Inacio', 2, 'luizinacio@gmail.com', 'bla');
INSERT INTO users (full_name,type,email,password) VALUES ('Alon Dangaur', 1, 'alondx2@gmail.com', 'bla');
INSERT INTO users (full_name,type,email,password) VALUES ('Gabriel abu', 3, 'benjaminnetanyahu@gmail.com', '123');
INSERT INTO users (full_name,type,email,password) VALUES ('Ido kaka', 3, 'idokaka@gmail.com', '234');
INSERT INTO users (full_name,type,email,password) VALUES ('Blu ash', 2, 'bluash@gmail.com', '098');
INSERT INTO users (full_name,type,email,password) VALUES ('Arthur L', 2, 'arthurl@gmail.com', 'asdf');
INSERT INTO users (full_name,type,email,password) VALUES ('Katman Du', 1, 'katmandu@gmail.com', 'Katman Du');
INSERT INTO users (full_name,type,email,password) VALUES ('u', 1, 'u', 'u');
INSERT INTO users (full_name,type,email,password) VALUES ('d', 2, 'd', 'd');
INSERT INTO users (full_name,type,email,password) VALUES ('t', 3, 't', 't');


INSERT INTO products (productName) VALUES ('WebApp1');
INSERT INTO products (productName) VALUES ('WebApp2');

INSERT INTO taskTypes (taskType) VALUES ('Installation');
INSERT INTO taskTypes (taskType) VALUES ('Configuration');

INSERT INTO environments (envName) VALUES ('Beta');
INSERT INTO environments (envName) VALUES ('UAT');
INSERT INTO environments (envName) VALUES ('Production');

INSERT INTO status (statusName) VALUES ('New');
INSERT INTO status (statusName) VALUES ('In Progress');
INSERT INTO status (statusName) VALUES ('In QA Progress');
INSERT INTO status (statusName) VALUES ('Done');
INSERT INTO status (statusName) VALUES ('Fail');

INSERT INTO priority (priorityName) VALUES ('High');
INSERT INTO priority (priorityName) VALUES ('Medium');
INSERT INTO priority (priorityName) VALUES ('Low');
INSERT INTO priority (priorityName) VALUES ('Irrelevant');

DROP PROCEDURE IF EXISTS `addTask`;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `addTask`
(
    IN taskTypeId int,
    IN productId int,
    IN envId int,
    IN requesterId int,
    IN priorityId int,
    IN open_date DATE,
    IN statusId int,
    IN qaGO bool,
    IN rollBack bool,
    IN urgent bool,
    IN additionalInfo TEXT
)
BEGIN
     INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id)
     VALUE (taskTypeId,productId,envId,requesterId,priorityId,open_date,NULL,statusId,qaGO,rollBack,urgent,additionalInfo,NULL,NULL);
END;
$$


CREATE OR REPLACE VIEW v_Tasks AS
SELECT t.id, open_date, statusName as status, exec_date, taskType
FROM tasks t
JOIN taskTypes tt on t.taskTypeId = tt.id
JOIN status s on t.statusId = s.id ORDER BY id;

CREATE OR REPLACE VIEW v_Users AS
SELECT u.id,full_name,ut.userType as type,email,password
FROM users u
JOIN userTypes ut on u.type = ut.id
ORDER BY u.id;


INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id)
VALUE (1, 1, 3, 2, 1, '2017-03-11', '2017-03-11', 1, 1, 1, 0, NULL, NULL, NULL);

-- CALL addTask (1, 2, 3, 1, 2, '2017-03-11',1, 1, 1, 0,'this is a test' );


INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id)
VALUE (1, 1, 3, 2, 1, '2017-03-11', '2017-03-10', 1, 1, 1, 0, NULL, NULL, NULL);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id)
VALUE (1, 1, 3, 2, 1, '2017-03-09', '2017-03-10', 2, 1, 1, 0, NULL, NULL, NULL);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id)
VALUE (1, 1, 3, 2, 1, '2017-03-15', '2017-03-17', 1, 1, 1, 0, NULL, NULL, NULL);




INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 2,3, '2017-03-22', '2018-07-18',5, 1, 1, 0, 'iscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id.', 7, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 6,2, '2017-02-28', '2018-05-16',5, 1, 1, 0, 'sum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus a', 9, 1);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 2, 2,1, '2017-08-19', '2018-05-12',3, 1, 1, 0, 'm dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accums', NULL, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 8,3, '2017-02-12', '2018-08-14',1, 1, 1, 0, 'etur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus ', 1, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 1,3, '2017-08-12', '2018-04-23',3, 1, 1, 0, 'm dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus', 4, NULL);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 2, 4,2, '2017-05-13', '2018-08-29',5, 1, 1, 0, 'l ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus acc', 5, 7);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 3,1, '2017-08-26', '2018-09-27',4, 1, 1, 0, 's. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisq', 7, 7);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 4,4, '2017-02-27', '2018-03-19',5, 1, 1, 0, 'm mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidun', 8, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 5,2, '2017-08-14', '2018-01-23',3, 1, 1, 0, 'bendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, ', NULL, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 8,1, '2017-08-27', '2018-09-12',5, 1, 1, 0, 'tetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sag', 9, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 1,1, '2017-01-15', '2018-02-23',4, 1, 1, 0, 'piscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultric', NULL, NULL);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 3,2, '2017-01-16', '2018-02-18',1, 1, 1, 0, 'el ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibu', 3, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 2,3, '2017-02-13', '2018-08-27',3, 1, 1, 0, 'ollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turp', 2, 5);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 8,4, '2017-03-14', '2018-05-13',1, 1, 1, 0, 'amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris.', 7, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 6,3, '2017-09-19', '2018-05-18',3, 1, 1, 0, 'dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae ', 5, NULL);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 7,4, '2017-09-22', '2018-07-11',1, 1, 1, 0, ' amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibu', 8, 7);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 2,3, '2017-05-22', '2018-09-28',2, 1, 1, 0, 'em ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris', NULL, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 7,4, '2017-03-26', '2018-08-17',3, 1, 1, 0, ' sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis ', 7, 2);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 7,1, '2017-03-13', '2018-07-18',4, 1, 1, 0, ' elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpi', 7, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 1,4, '2017-02-12', '2018-01-25',4, 1, 1, 0, 'ipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis', 2, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 6,1, '2017-05-27', '2018-07-21',4, 1, 1, 0, 'h bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pelle', 5, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 8,3, '2017-03-12', '2018-08-12',2, 1, 1, 0, 'l ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Q', 8, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 8,1, '2017-09-19', '2018-03-28',4, 1, 1, 0, 'llis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae t', 4, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 6,3, '2017-08-21', '2018-03-22',3, 1, 1, 0, 'ur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, v', 7, 2);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 6,4, '2017-01-16', '2018-05-24',5, 1, 1, 0, 't amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accum', 3, 5);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 2,3, '2017-03-16', '2018-07-16',2, 1, 1, 0, 'et, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae ti', 4, 2);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 3,4, '2017-02-17', '2018-02-23',3, 1, 1, 0, 'lis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellentesque lacinia tempor. Donec dignissim in est', 8, 3);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 1,3, '2017-05-16', '2018-06-11',2, 1, 1, 0, 'lit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis,', 3, NULL);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 2,1, '2017-02-21', '2018-09-13',5, 1, 1, 0, 'el ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctu', 8, 2);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 6,2, '2017-04-21', '2018-02-16',1, 1, 1, 0, 'llis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellentesque lacinia tempor. Donec dignissim in ', 7, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 7,4, '2017-05-27', '2018-03-24',4, 1, 1, 0, 'olor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget cons', 2, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 7,4, '2017-08-14', '2018-04-25',2, 1, 1, 0, 'ecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tem', 2, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 2, 3,3, '2017-07-26', '2018-06-13',5, 1, 1, 0, 'r adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Ves', 3, 7);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 7,3, '2017-04-17', '2018-01-22',4, 1, 1, 0, 'id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus ', 1, 5);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 2, 8,3, '2017-02-27', '2018-06-13',3, 1, 1, 0, 't. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisqu', 1, 2);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 6,4, '2017-04-14', '2018-03-26',1, 1, 1, 0, 'lit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan t', NULL, NULL);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 2, 1,2, '2017-01-15', '2018-09-19',3, 1, 1, 0, ' vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus', 5, NULL);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 8,3, '2017-08-25', '2018-03-22',3, 1, 1, 0, 'em ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur', 3, 7);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 2, 4,1, '2017-04-23', '2018-02-28',1, 1, 1, 0, 'um id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vit', 7, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 3,3, '2017-01-22', '2018-07-16',1, 1, 1, 0, 'rem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauri', 5, 7);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 2, 8,3, '2017-03-16', '2018-04-16',1, 1, 1, 0, ' amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Viva', 4, 1);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 5,2, '2017-01-14', '2018-08-17',5, 1, 1, 0, 'dum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellentesque lacinia tempor.', 5, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 7,2, '2017-08-16', '2018-02-24',4, 1, 1, 0, 'scing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vita', 6, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 2,4, '2017-08-26', '2018-04-27',3, 1, 1, 0, ' mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan tur', 1, 3);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 8,2, '2017-05-29', '2018-07-28',5, 1, 1, 0, 'g elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum l', 4, 3);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 3,3, '2017-02-14', '2018-05-28',5, 1, 1, 0, 'elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id', 2, 5);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 7,4, '2017-06-27', '2018-04-17',2, 1, 1, 0, 'lis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros', 2, 5);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 4,1, '2017-05-21', '2018-02-11',4, 1, 1, 0, 'cing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpi', 6, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 5,4, '2017-06-12', '2018-06-16',2, 1, 1, 0, 'h bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tin', NULL, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 9,4, '2017-09-16', '2018-04-22',3, 1, 1, 0, ' nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellentesque l', 8, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 2,2, '2017-08-14', '2018-07-25',3, 1, 1, 0, 'bh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellente', 1, NULL);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 2, 5,4, '2017-02-17', '2018-08-11',5, 1, 1, 0, 'lor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Ves', 6, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 8,2, '2017-04-22', '2018-04-15',1, 1, 1, 0, 'nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellente', 5, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 2, 7,4, '2017-04-14', '2018-01-18',5, 1, 1, 0, 'nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pe', 9, 5);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 2, 8,2, '2017-01-18', '2018-08-17',4, 1, 1, 0, 'ing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctu', 9, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 6,3, '2017-09-25', '2018-07-22',5, 1, 1, 0, 'sum dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus', 4, 2);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 8,4, '2017-07-23', '2018-03-14',2, 1, 1, 0, 'orem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibul', 2, NULL);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 4,4, '2017-03-17', '2018-03-26',1, 1, 1, 0, 'or sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibul', 5, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 9,1, '2017-03-27', '2018-03-26',1, 1, 1, 0, 'tetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. ', 8, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 7,2, '2017-04-13', '2018-01-29',4, 1, 1, 0, 'ng elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vesti', 4, 1);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 5,1, '2017-01-25', '2018-03-23',5, 1, 1, 0, 'llis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pe', 1, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 9,1, '2017-07-25', '2018-01-18',5, 1, 1, 0, 'et, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis ', 7, 7);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 2, 1,4, '2017-01-13', '2018-06-18',4, 1, 1, 0, 'cing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque ', 2, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 2,2, '2017-04-25', '2018-04-14',4, 1, 1, 0, 'psum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt er', 1, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 3,4, '2017-01-17', '2018-07-16',1, 1, 1, 0, 'Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turp', 5, 5);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 9,3, '2017-09-26', '2018-04-26',4, 1, 1, 0, 'm mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, v', 8, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 8,3, '2017-06-11', '2018-02-26',2, 1, 1, 0, 'el ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan t', 1, 3);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 5,4, '2017-01-12', '2018-02-27',1, 1, 1, 0, 'adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vest', 3, 3);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 6,3, '2017-06-13', '2018-09-26',3, 1, 1, 0, 'mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt ero', 7, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 2, 8,3, '2017-03-29', '2018-07-15',2, 1, 1, 0, 't, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros', 4, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 9,4, '2017-05-17', '2018-07-15',5, 1, 1, 0, 'enas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus ', 1, 1);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 1,3, '2017-07-11', '2018-06-17',1, 1, 1, 0, 'um dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur ', 9, 2);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 8,4, '2017-03-18', '2018-05-21',4, 1, 1, 0, 'dipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis t', 9, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 9,4, '2017-07-15', '2018-04-23',3, 1, 1, 0, ' adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ', 9, 2);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 1,3, '2017-01-22', '2018-08-14',5, 1, 1, 0, ' vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ul', 8, 1);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 2, 4,4, '2017-03-24', '2018-04-26',2, 1, 1, 0, ', consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accu', 1, NULL);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 3,2, '2017-04-13', '2018-02-28',5, 1, 1, 0, 's vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan', 4, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 8,1, '2017-02-21', '2018-08-23',5, 1, 1, 0, 't. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum lu', 7, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 2, 7,3, '2017-03-17', '2018-01-17',2, 1, 1, 0, 'tetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamu', 9, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 2,3, '2017-05-17', '2018-02-11',5, 1, 1, 0, 'd nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellent', NULL, 2);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 4,2, '2017-04-21', '2018-08-18',1, 1, 1, 0, 'met, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus', 5, NULL);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 2, 5,3, '2017-09-19', '2018-01-17',3, 1, 1, 0, 'mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellentesque lacinia tempor. Donec ', 5, 5);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 2,1, '2017-08-24', '2018-08-24',1, 1, 1, 0, 'ollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pe', 6, 3);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 3,1, '2017-05-28', '2018-06-25',4, 1, 1, 0, 'um mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellentesque lacinia ', NULL, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 3,1, '2017-06-21', '2018-09-27',2, 1, 1, 0, ' amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempu', 6, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 4,2, '2017-05-27', '2018-06-27',2, 1, 1, 0, 'ing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt ', 9, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 7,4, '2017-06-15', '2018-07-19',4, 1, 1, 0, '. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, v', 7, 3);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 2,4, '2017-04-22', '2018-01-24',4, 1, 1, 0, 'met, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpi', 4, 3);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 2, 1,4, '2017-01-13', '2018-04-23',3, 1, 1, 0, 'sum dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget cons', 2, 3);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 2, 9,4, '2017-09-24', '2018-06-23',5, 1, 1, 0, ' vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vest', 5, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 2, 1,4, '2017-07-14', '2018-06-16',5, 1, 1, 0, 'et, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan tu', 8, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 9,3, '2017-06-12', '2018-02-18',4, 1, 1, 0, 'd nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellentesque lacinia tempo', 7, 3);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 2,4, '2017-01-26', '2018-03-19',2, 1, 1, 0, ' id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae ', 7, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 9,3, '2017-09-21', '2018-04-23',5, 1, 1, 0, ' nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsa', 1, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 7,3, '2017-09-29', '2018-05-16',1, 1, 1, 0, 'lis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae ', 6, 5);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 8,4, '2017-01-14', '2018-09-22',2, 1, 1, 0, ' consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan', NULL, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 4,2, '2017-09-23', '2018-09-21',2, 1, 1, 0, 'dum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae ti', 7, 5);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 2, 4,4, '2017-04-23', '2018-04-13',3, 1, 1, 0, 't, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus ', 7, 7);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 4,3, '2017-06-16', '2018-02-12',2, 1, 1, 0, 'sum dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vi', 6, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 4,3, '2017-09-24', '2018-06-22',4, 1, 1, 0, 'as vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellent', 6, 5);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 9,4, '2017-02-17', '2018-03-21',1, 1, 1, 0, 'um dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vit', 5, 3);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 2, 7,3, '2017-09-18', '2018-04-13',5, 1, 1, 0, 'sectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus ', 4, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 7,3, '2017-06-22', '2018-02-21',2, 1, 1, 0, 'scing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt e', 4, 7);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 2,4, '2017-06-27', '2018-03-19',3, 1, 1, 0, 'em ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget co', 2, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 7,3, '2017-03-15', '2018-09-23',1, 1, 1, 0, 'rem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus.', 6, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 5,2, '2017-07-18', '2018-04-21',1, 1, 1, 0, 't. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus ac', 3, NULL);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 2, 1,3, '2017-07-26', '2018-08-22',1, 1, 1, 0, ' Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisq', NULL, 3);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 5,4, '2017-03-21', '2018-02-15',3, 1, 1, 0, 'nsectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis', 3, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 6,4, '2017-03-22', '2018-09-14',3, 1, 1, 0, ' mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis,', 7, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 2, 2,4, '2017-03-24', '2018-06-21',5, 1, 1, 0, 'Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pe', 8, 7);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 4,2, '2017-09-15', '2018-07-18',4, 1, 1, 0, ' ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum l', 7, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 5,4, '2017-05-13', '2018-06-26',2, 1, 1, 0, 'et, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luc', 9, 2);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 2, 6,2, '2017-01-21', '2018-02-16',5, 1, 1, 0, 'et, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidun', 7, 2);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 1,3, '2017-02-12', '2018-09-21',2, 1, 1, 0, ' sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt', 8, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 4,2, '2017-07-19', '2018-03-26',1, 1, 1, 0, 'm id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque p', 8, 3);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 4,2, '2017-07-22', '2018-01-29',2, 1, 1, 0, 'aecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidu', 4, 1);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 7,1, '2017-05-26', '2018-02-11',1, 1, 1, 0, 'm mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque ', 4, 1);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 1,1, '2017-01-18', '2018-06-23',4, 1, 1, 0, 's. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellentesq', 9, 1);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 1,3, '2017-04-23', '2018-03-27',4, 1, 1, 0, '. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices i', 9, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 2,1, '2017-09-26', '2018-09-14',2, 1, 1, 0, 'ing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ', 3, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 2,3, '2017-04-12', '2018-05-19',2, 1, 1, 0, ' elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidun', 7, 7);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 2,3, '2017-05-22', '2018-02-23',3, 1, 1, 0, 'llis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellentesque lacinia tempor. Donec dignissim in e', 9, NULL);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 2, 4,2, '2017-04-12', '2018-01-23',3, 1, 1, 0, 'm mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pe', NULL, 5);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 8,3, '2017-09-28', '2018-07-17',1, 1, 1, 0, 'etur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivam', 2, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 2, 4,1, '2017-01-25', '2018-07-26',1, 1, 1, 0, 'bh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellen', 9, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 1,3, '2017-08-28', '2018-08-24',4, 1, 1, 0, ' consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus acc', 5, 3);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 3,1, '2017-09-17', '2018-05-27',1, 1, 1, 0, 'l ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices ', 5, 5);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 5,2, '2017-06-19', '2018-04-21',3, 1, 1, 0, 'it amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Ves', 7, 1);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 9,4, '2017-06-18', '2018-09-19',5, 1, 1, 0, 'onsectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices', 4, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 5,1, '2017-07-22', '2018-01-12',2, 1, 1, 0, 'nas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. ', 1, 7);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 2, 8,3, '2017-05-16', '2018-09-27',5, 1, 1, 0, ' adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ', 5, 2);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 3,1, '2017-09-17', '2018-09-14',5, 1, 1, 0, 'ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis', 8, 7);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 5,3, '2017-06-26', '2018-05-16',5, 1, 1, 0, ' ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellentesque laci', 1, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 2, 3,2, '2017-03-12', '2018-01-14',2, 1, 1, 0, 'dipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Ves', 8, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 4,4, '2017-07-14', '2018-09-22',2, 1, 1, 0, ' elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, ', 7, 5);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 1,2, '2017-03-15', '2018-07-15',1, 1, 1, 0, ' amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis ', 8, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 7,3, '2017-04-13', '2018-02-25',5, 1, 1, 0, ' vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque', 3, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 8,3, '2017-09-24', '2018-09-13',1, 1, 1, 0, 'ng elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellen', 1, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 9,3, '2017-09-14', '2018-02-19',3, 1, 1, 0, 'm dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mol', 8, 1);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 6,2, '2017-01-23', '2018-03-27',5, 1, 1, 0, 't amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidun', 7, 2);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 9,1, '2017-02-18', '2018-09-15',3, 1, 1, 0, 'um dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis', 6, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 4,1, '2017-09-21', '2018-05-17',1, 1, 1, 0, 't amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur m', 2, 1);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 2, 5,2, '2017-06-26', '2018-02-26',1, 1, 1, 0, 'r adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestib', NULL, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 9,2, '2017-08-15', '2018-08-26',4, 1, 1, 0, 'bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellentesque lacinia tempor. Donec di', NULL, NULL);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 1,4, '2017-03-16', '2018-03-29',2, 1, 1, 0, 'nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ult', 1, 2);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 1,4, '2017-01-27', '2018-02-28',4, 1, 1, 0, ' id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tinc', 6, 3);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 7,3, '2017-01-23', '2018-04-12',3, 1, 1, 0, 'm id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidun', 3, NULL);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 6,1, '2017-04-11', '2018-06-22',4, 1, 1, 0, 'el ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae t', 4, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 2, 4,4, '2017-05-14', '2018-08-22',4, 1, 1, 0, 'dipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. V', 8, 1);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 8,1, '2017-03-27', '2018-02-11',5, 1, 1, 0, ' ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pell', 3, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 1,3, '2017-05-11', '2018-02-18',5, 1, 1, 0, 'sectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, ', 3, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 8,4, '2017-08-15', '2018-08-23',5, 1, 1, 0, 'g elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tinci', 4, 5);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 8,4, '2017-07-13', '2018-03-26',5, 1, 1, 0, 'cenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ', 2, 7);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 6,3, '2017-08-17', '2018-07-15',5, 1, 1, 0, 'bh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ul', 7, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 8,1, '2017-02-26', '2018-07-15',4, 1, 1, 0, 'amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis t', 1, 3);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 6,3, '2017-02-18', '2018-01-17',1, 1, 1, 0, 'rem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tem', 1, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 7,3, '2017-05-19', '2018-06-28',4, 1, 1, 0, 'ibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae ', 3, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 8,2, '2017-03-17', '2018-01-29',3, 1, 1, 0, 'g elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan tur', 5, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 2, 7,1, '2017-01-22', '2018-05-26',3, 1, 1, 0, 't amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus a', 3, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 2, 4,1, '2017-01-28', '2018-05-26',5, 1, 1, 0, 'Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisqu', 2, 1);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 2, 5,3, '2017-04-12', '2018-09-17',3, 1, 1, 0, 'ng elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mol', 1, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 2, 6,1, '2017-06-24', '2018-03-25',2, 1, 1, 0, 'ng elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tinc', 9, 7);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 2, 8,1, '2017-02-27', '2018-08-18',3, 1, 1, 0, 'tetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagi', 1, 2);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 4,3, '2017-02-19', '2018-09-12',5, 1, 1, 0, ' nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisq', 5, 1);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 2,2, '2017-07-23', '2018-02-24',3, 1, 1, 0, ' mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellentesque lacinia tempor. Donec d', 8, NULL);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 1,3, '2017-05-22', '2018-07-21',1, 1, 1, 0, 'r adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id.', 3, 5);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 6,1, '2017-08-12', '2018-04-13',2, 1, 1, 0, ' nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellentesque l', 5, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 7,4, '2017-05-28', '2018-07-29',5, 1, 1, 0, ' elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices i', 7, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 4,2, '2017-05-12', '2018-06-19',2, 1, 1, 0, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consecte', 2, 3);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 3,4, '2017-03-23', '2018-03-16',5, 1, 1, 0, 'onsectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis ', 7, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 2, 1,2, '2017-05-24', '2018-05-11',3, 1, 1, 0, 'or sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan tu', 5, 1);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 7,3, '2017-06-21', '2018-01-16',3, 1, 1, 0, 'as vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luc', 5, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 3,1, '2017-03-23', '2018-08-28',4, 1, 1, 0, 'it. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum', 5, 5);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 7,4, '2017-06-28', '2018-01-13',1, 1, 1, 0, 'nas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsa', NULL, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 9,2, '2017-04-13', '2018-08-17',5, 1, 1, 0, ' mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellentesque lacinia', 4, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 4,2, '2017-07-23', '2018-04-21',1, 1, 1, 0, 'um id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellentesque lacinia tem', 3, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 3,3, '2017-09-17', '2018-02-19',1, 1, 1, 0, 't, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibu', 7, 2);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 6,4, '2017-02-18', '2018-01-28',3, 1, 1, 0, 'r adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus a', 9, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 5,3, '2017-06-24', '2018-09-25',4, 1, 1, 0, 'bendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellen', NULL, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 1,1, '2017-05-24', '2018-02-23',5, 1, 1, 0, 'ecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accums', 4, 1);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 5,4, '2017-05-26', '2018-05-13',2, 1, 1, 0, 'psum dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectet', 2, 2);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 5,2, '2017-03-12', '2018-03-15',5, 1, 1, 0, 'ndum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt ', 4, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 5,1, '2017-02-27', '2018-06-22',5, 1, 1, 0, 'ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget co', 4, 3);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 2,4, '2017-08-18', '2018-02-25',4, 1, 1, 0, 'onsectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultr', 3, 8);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 6,1, '2017-05-21', '2018-03-18',3, 1, 1, 0, 'mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae ti', 4, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 2, 2,4, '2017-09-27', '2018-03-24',4, 1, 1, 0, 'iscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis ', 7, 2);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 1, 1,4, '2017-08-12', '2018-03-14',5, 1, 1, 0, 'dolor sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis', 5, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 2, 5,3, '2017-03-17', '2018-08-17',2, 1, 1, 0, 'l ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan', 7, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 1, 1, 7,2, '2017-03-14', '2018-06-27',3, 1, 1, 0, 'lis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellentesque la', 3, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 3,4, '2017-07-28', '2018-04-27',5, 1, 1, 0, ' sit amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum l', 7, NULL);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 7,1, '2017-04-28', '2018-07-18',1, 1, 1, 0, 'met, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mau', 7, 6);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (1, 2, 2, 4,2, '2017-05-23', '2018-08-25',4, 1, 1, 0, 'amet, consectetur adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accum', 9, 9);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 1,3, '2017-06-12', '2018-03-16',5, 1, 1, 0, ' adipiscing elit. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagit', 7, 4);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 2, 1, 3,1, '2017-08-14', '2018-03-16',2, 1, 1, 0, '. Maecenas vel ipsum id nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus ', 2, 7);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 1, 1,1, '2017-02-21', '2018-01-26',5, 1, 1, 0, ' nibh bibendum mollis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros', 6, NULL);
INSERT INTO tasks (taskTypeId,productId,envId,requesterId,priorityId,open_date,exec_date,statusId,qaGO,rollBack,urgent,additionalInfo,assigneeId,resolved_by_Id) VALUES (2, 1, 2, 5,4, '2017-07-11', '2018-03-18',1, 1, 1, 0, 'llis. Mauris eget consectetur mauris. Vivamus sagittis mollis tempus. Vestibulum luctus accumsan turpis, vitae tincidunt eros ultrices id. Quisque pellentesque lacinia tempor. Donec dignissim in ', 1, 9);
